#!/bin/bash
export XDG_RUNTIME_DIR=/run/user/$(id -u)

BATTINFO=`acpi -b`
if [[ `echo $BATTINFO | grep Discharging` ]] ; then
    if [[ `echo $BATTINFO | cut -f 5 -d " "` < 00:30:00 ]] ; then
        DISPLAY=:0.0 /usr/bin/notify-send "Low battery" "$BATTINFO"
    elif [[ `echo $BATTINFO | cut -f 4 -d " " | cut -f 1 -d "%"` < 55
         && `echo $BATTINFO | cut -f 4 -d " " | cut -f 1 -d "%"` > 45 ]] ; then
        DISPLAY=:0.0 /usr/bin/notify-send "Half battery" "$BATTINFO"
    fi
fi
