#!/usr/bin/env bash

# Terminate already running bar instances
killall xwinwrap

# Wait until the processes have been shut down
while pgrep -u $UID -x xwinwrap >/dev/null; do sleep 1; done

# Launch bar1 and bar2
xrandr | grep -sw "connected" | grep -soP "\d+x\S+" | while read -r line ; do
    ~/.scripts/gifbg $line &
done
#~/.scripts/mpvbg second &

echo "Background launched..."
