#!/usr/bin/env python3
import os,random,sys
wpDir = os.path.expanduser('~') + "/.wallpapers"
bg = random.choice(os.listdir(wpDir))

cmd = 'xwinwrap -g %s -ov -- mpv --wid WID %s/%s --loop --no-osc' % (sys.argv[1], wpDir,bg)
os.system(cmd)
