#!/usr/bin/env bash

# Terminate already running bar instances
killall xwinwrap

# Wait until the processes have been shut down
while pgrep -u $UID -x xwinwrap >/dev/null; do sleep 1; done

# Launch bar1 and bar2
~/.scripts/mpvbg &

echo "Background launched..."
