#!/bin/bash
out="$HOME/Pictures/Screencasts/$(date +%F-%H-%M-%S)"

dmn=$(echo -e "Microphone\nMonitor" | rofi -dmenu -multi-select)
[[ "$dmn" == *"Microphone"* ]] && mic=1 && src="-f pulse -i 0"
[[ "$dmn" == *"Monitor"* ]] && mon=1 && src="$src -f pulse -i $(pactl list short sinks | grep RUNNING | awk '{print $2}').monitor"
[[ 2 -eq $((mic+mon)) ]] && src="$src -filter_complex amix=inputs=2"

read -r X Y W H G ID < <(slop -f "%x %y %w %h %g %i")
ffmpeg -f x11grab -s "$W"x"$H" -i :0.0+$X,$Y $src "$out.mkv"

dmn=$(echo -e "GIF\nWEBM" | rofi -dmenu -multi-select)
[[ "$dmn" == *"GIF"* ]] && ffmpeg -i "$out.mkv" "$out.gif"
[[ "$dmn" == *"WEBM"* ]] && ffmpeg -i "$out.mkv" "$out.webm"

notify-send "size $(du -h $out.* | awk '{print $1}')"
