#! /bin/sh
BTERM=urxvt

xset b off
xset -dpms
xset s noblank
xset s off
xinput --disable 'AlpsPS/2 ALPS DualPoint TouchPad'
setxkbmap -variant mac -option 'caps:swapescape,compose:rctrl'

sxhkd &

bspc monitor eDP-1 -d I II III IV V
bspc monitor DP-2 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          50

bspc config split_ratio          0.52
bspc config right_padding        325


bspc rule -a discord desktop='I' follow=on
bspc rule -a Telegram desktop='I'

bspc rule -a firefox desktop='II'

bspc rule -a \*:ws3 desktop='III'

bspc rule -a Steam desktop='IV' follow=on
bspc rule -a Gimp desktop='IV' follow=on

bspc rule -a Thunderbird desktop='V'

bspc rule -a Lxappearance state=floating
bspc rule -a \*:cava state=floating sticky=on
bspc rule -a firefox:Toolkit sticky=on

~/.scripts/bspwm_steam


# Autostart
startup_lock_file=/tmp/bspwm-startup.lock
if [ ! -f $startup_lock_file ]; then
    touch $startup_lock_file
	feh --bg-fill --randomize ~/.wallpapers

    my_laptop_external_monitor=$(xrandr --query | grep 'DP-1')
    if [[ $my_laptop_external_monitor = *connected* ]]; then
        xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-1 --off --output HDMI-1 --off --output DP-2 --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-2 --off
    fi

    urxvt -geometry 33x14-25-25 -name 'cava' -bg "[58]#06060a" -e cava &
	$BTERM -name 'ws3' &
    udiskie --tray -A &
	picom -f -D 5 &
	xfce4-clipman &
	redshift-gtk &
    blueman-applet &
	polybar-start
	nm-applet &
	dunst &
    conky & (sleep 2 && mpvbg-start)
fi
