#! /bin/sh
BTERM=urxvt

xset b off
xset -dpms
xset s noblank
xset s off
xinput --disable 'AlpsPS/2 ALPS DualPoint TouchPad'
setxkbmap -variant mac -option 'caps:swapescape,compose:rctrl'

sxhkd &

monitor2=$(xrandr --query | grep 'DP-2')
monitor3=$(xrandr --query | grep 'HDMI-1')
#if [[ $monitor2 = *connected* ]]; then
#    if [[ $monitor3 = *connected* ]]; then
#        prim='DP-2'
#        seco='HDMI-1'
#        edp1='--output eDP-1 --off'
#    else
#        prim='eDP-1'
#        seco='DP-2'
#    fi
#    xrandr $edp1 --output $seco --mode 1920x1080 --output $prim --primary --right-of $seco --mode 1920x1080
#    bspc monitor $seco -d VI VII VIII IX X
#else
#    prim='DP-2'
#    seco='eDP-1'
#fi
# TODO more power, uncommment
if xrandr --query | grep "HDMI-1" | grep -qsw "connected"; then
    prim='HDMI-1'
    offm='eDP-1'
elif xrandr --query | grep "DP-2" | grep -qsw "connected"; then
    prim="DP-2"
    offm="eDP-1"
else
    prim='eDP-1'
    offm='DP-2'
fi

xrandr --output $offm --off --output $prim --primary --mode 1920x1080 

if [ ! -f /tmp/bspwm-startup.lock ]; then
    bspc monitor $prim -d I II III IV V
else
    bspc monitor $offm -a dummy
    bspc query --desktops --names | while read -r line; do [[ $line == "dummy" ]] || bspc desktop $line -m $prim; done
    bspc desktop Desktop --remove
fi
bspc monitor $offm --remove

bspc config border_width           2
bspc config window_gap             50

bspc config split_ratio            0.52
bspc config right_padding 335


bspc rule -a discord desktop='I' follow=on
bspc rule -a Telegram desktop='I'

bspc rule -a firefox desktop='II'

bspc rule -a \*:ws3 desktop='III'

bspc rule -a Steam desktop='IV' follow=on
bspc rule -a Gimp desktop='IV' follow=on

bspc rule -a Thunderbird desktop='V'

bspc rule -a Lxappearance state=floating
bspc rule -a \*:stick state=floating layer=normal sticky=on
bspc rule -a \*:above state=floating layer=above sticky=on
bspc rule -a \*:below state=floating layer=below sticky=on 
bspc rule -a firefox:Toolkit sticky=on

~/.scripts/bspwm_steam

# Autostart
startup_lock_file=/tmp/bspwm-startup.lock
if [ ! -f $startup_lock_file ]; then
    touch $startup_lock_file

    urxvt -geometry 33x12-25-63 -name 'stick' -bg "[30]#06060a" -e cava &
    urxvt -geometry 33x12-25-63 -name 'below' -bg "[58]#06060a" -e cmatrix &
    kdeconnect-indicator &
	$BTERM -name 'ws3' &
    udiskie --tray -A &
	picom -f -D 5 &
	xfce4-clipman &
	redshift-gtk &
    blueman-applet &
	nm-applet &
	dunst &
    conky &
fi
polybar-start
sleep 2 && gifbg-start
