#! /bin/sh
BTERM=urxvt

sxhkd &

bspc monitor eDP-1 -d I II III IV V
bspc monitor DP-1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          50

bspc config split_ratio          0.52
bspc config focus_follows_pointer true


bspc rule -a discord desktop='I'
bspc rule -a Telegram desktop='I'

bspc rule -a firefox desktop='II'

bspc rule -a \*:ws3 desktop='III'

bspc rule -a Gimp desktop='V' follow=on
bspc rule -a \*:ws5 desktop='V'

bspc rule -a Lxappearance state=floating


# Autostart
startup_lock_file=/tmp/bspwm-startup.lock
if [ ! -f $startup_lock_file ]; then
    touch $startup_lock_file

	$BTERM -name 'ws3' &
	$BTERM -name 'ws3' &
	$BTERM -name 'ws5' &
	compton -f -D 5 &
	xfce4-clipmana &
	redshift-gtk &
	nm-applet &
	dunst &

	feh --bg-fill --randomize ~/.wallpapers
	polybar-start
	mpvbg-start
fi
